### ISSUE TITLE
Add attribution to images taken from ApacheCon

### ISSUE THREAD

**Issue by potiuk** [softwareguru/airflowsummit-website#16]
“Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.”
https://creativecommons.org/licenses/by/4.0/ (edited)

**Comment by pedrogk** [comment]
Done. Added credit in the footer.

**Comment by potiuk** [comment]
Love it !
